### ISSUE TITLE
[Question] Che-ls-jdt download location

### ISSUE THREAD

**Issue by yyoncho** [eclipse/che-ls-jdt#49]
I am working on emacs frontend (https://github.com/emacs-lsp/lsp-java) and I found https://github.com/theia-ide/theia/issues/1869 which mentions that `che-ls-jdt` provides some additional functionality and I would like to move `lsp-java` to it. What is the recommended way to obtain a build of `che-ls-jdt` (the equivalent of http://download.eclipse.org/jdtls/snapshots/) ?

**Comment by yyoncho** [comment]
@tsmaeder

**Comment by tsmaeder** [comment]
We're currently setting up ci on eclipse.org. Since yesterday, snapshot builds are published to http://download.eclipse.org/che/che-ls-jdt/snapshots/ As soon as we have proper releasese they'll be at http://download.eclipse.org/che/che-ls-jdt/milestones
